name: PR Review Reminder

on:
  pull_request_target:
    types: [opened]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: "⚠️ A maintainer should review this before it is merged. 🚀"
            });
